version: "3.9"

services:
  pycalendar:
    image: "spitileplusbeau/pycalendar:v3.1.0"
    hostname: '{{.Node.Hostname}}'
    volumes:
      - PyCalendar_Config:/app/config
      - PyCalendar_Log:/var/log
    environment:
      - TZ=Europe/Paris 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.pycalendar.rule=${TRAEFIK_RULE}
        - traefik.http.services.pycalendar.loadbalancer.server.port=5000
    networks:
      - traefik-public

volumes:
  PyCalendar_Log:
  PyCalendar_Config:
    external: true

networks:
  traefik-public:
    external: true
